### ISSUE TITLE
How to change magnifier level after loading?

### ISSUE THREAD

**Issue by kangchals** [scaleflex/js-cloudimage-360-view#10]
It  seems that there is no interface to change magnifier level after loading.

I am using vuejs and i tried to change data-magnifier attribute on runtime but it fails.

Can you add the feature??  or 
Can you give me any trick for handling them?? 

Thank you!!!

**Comment by dzmitry-stramavus** [comment]
hey @kangchals ,

you have a few options to do so

1. If you need to apply for only one instance of 360 product, you can update the value directly in the instance, like ```window.CI360._viewers[0].magnifier = 4```

see the code sandbox: https://codesandbox.io/s/js-cloudimage-360-view-change-magnifier-level-rfyyv

2. If you need to update several instances, you can change data-magnifier and reInitialize the plugin.  using init and destroy methods 
```window.CI360.destroy(); window.CI360.init()```

hope, it's what you are looking for
