### ISSUE TITLE
An example to use this library from Next JS application

### ISSUE THREAD

**Issue by IntuzNarendraB** [scaleflex/js-cloudimage-360-view#104]
Hi,

Can you please provide an example to use this library from Next JS application?

Thanks.

**Comment by amrw-js** [comment]
hey @IntuzNarendraB, you would init the plugin on the component mount and destroy it on the component unmount
```javascript
import 'js-cloudimage-360-view';

  useEffect(() => {
    window.CI360.init();
    return () => {
      window.CI360.destroy();
    };
  }, []);
```
