### ISSUE TITLE
Spin Logo after Play-Once

### ISSUE THREAD

**Issue by AxelF1977** [scaleflex/js-cloudimage-360-view#105]
Hi,

thanks for putting my idea in version 2.7. works great.

It would be nice, if the normal 360 Logo will apear after play-once, like it is without play-once

Thanks a lot

**Comment by amrw-js** [comment]
hey @AxelF1977, thanks for your feedback we already added this to version [v.2.7.1](https://github.com/scaleflex/js-cloudimage-360-view/releases/tag/2.7.1)
