### ISSUE TITLE
Sass linting failure with v2.7.0?

### ISSUE THREAD

**Issue by bjsswanson** [scaleflex/js-cloudimage-360-view#106]
Hi,

With the release of 2.7.0 yesterday it seems like we are encountering a new issue we did not experience with 2.6.0

Our mini-css-extract-plugin is now failing with a sass error:

_SassError: wrong number of arguments (4 for 3) for `rgb'
--
04-Nov-2021 18:03:44 | [INFO]             on line 76 of node_modules/js-cloudimage-360-view/dist/static/css/style.css
04-Nov-2021 18:03:44 | [INFO]     >>   box-shadow: rgb(255, 255, 255, 0.5) 0px 0px 4px;_

Just wanted to flag as we do not believe we have changed any of our sass compilation or linting rules.

Thanks.

**Comment by amrw-js** [comment]
hey @bjsswanson, thanks for your feedback
we are going to fix this issue in the next release, the estimated time is today

**Comment by amrw-js** [comment]
thanks @bjsswanson, this mentioned issue has been fixed in [v2.7.1](https://github.com/scaleflex/js-cloudimage-360-view/releases/tag/2.7.1)
