### ISSUE TITLE
Responsive images with custom CDN

### ISSUE THREAD

**Issue by burakkaraceylan** [scaleflex/js-cloudimage-360-view#107]
Hello,

I would like to use this script, however I have my own CDN and I don't plan on using cloudimage CDN service. But, it seems the cloudimage servers are hardcoded into the script. Is there any way to use this with my own resizing CDN that I am missing or do I have to change the source code for this?

Thank you,
Burak

**Comment by amrw-js** [comment]
hello @burakkaraceylan, currently the plugin is responsive make sure to have the [latest version](https://github.com/scaleflex/js-cloudimage-360-view/releases/tag/v2.7.2) installed.
please note that you can create a free Cloudimage account and get a token for free. This token allows you to use upto 25GB of image cache and 25GB of worldwide CDN traffic per month for free.
