### ISSUE TITLE
data-drag-speed problem in iframe

### ISSUE THREAD

**Issue by sarbudeenmca** [scaleflex/js-cloudimage-360-view#109]
Drag speed is very higher if I use iframe. Image frame is changed every single pixel while of drag movement.
data-drag-speed / drag-speed is not working only when I using an iframe.

**Comment by ErensuGul** [comment]
Hello,

I was having the same problem as you, but I understood the cause of the problem. If you are calling the iFrame code in the background, this will cause the animation to generate a bug. If you have to call it in the background, assign a button to it with the help of jquery and onclick. This is how I implemented a solution.

I hope you can solve the problem.
