### ISSUE TITLE
help  canvas/transform/scale zoom and magnify works fine

### ISSUE THREAD

**Issue by kangchals** [scaleflex/js-cloudimage-360-view#11]
Hi!

Is there any way to adjust position and level of magnifier zoom  when image canvas is zoomed with transform scale ?

I add feature for zoom-in-out image using css transform scale.

It works fine but after zoom in or out, magnifier is working on origin image so it looks bad.

I checked source code and moveMagnifier and magnify is related but I failed to achieve my goal.

Can you give me some tip?? Thank you!!!!!!!!!

**Comment by dzmitry-stramavus** [comment]
hey @kangchals ,

pls, describe to us what you are trying to achieve, and probably we will add this feature to the plugin :)

**Comment by kangchals** [comment]
Sorry for my fool description.

Below is source code what I tried.

https://github.com/kangchals/js-cloudimage-360-view 

I scaled up target image with 

`trasform: scale(2);` on `canvas` element

After scaling the image, the position of the magnifier is not correct.

Is there any way to fit the location of magnifier?? 

Thank you!!!

**Comment by kangchals** [comment]
I have one more question which is not related to this one.

Do you know why npm install different codes between 

`npm install js-cloudimage-360-view`  and
`npm install ../js-cloudimage-360-view`

First one is from github and second one is from my local machine which is cloned from this repository.

I thought that they should operate same way but it wasn't.....
