### ISSUE TITLE
Next & Prev controls fire on mousedown

### ISSUE THREAD

**Issue by MarkoMZ** [scaleflex/js-cloudimage-360-view#111]
When using the controls (<button class="cloudimage-360-prev"></button> for example), they trigger on mousedown and sometimes do not stop => clicking with a longer mousedown just makes the 360 view go crazy and loop through every image very fast!

**Comment by amrw-js** [comment]
@MarkoMZ  thanks for debugging, I didn't manage to reproduce can you please provide more details or reproduce steps?
