### ISSUE TITLE
When using data-image-list: crashes because of requestResizedImages() function

### ISSUE THREAD

**Issue by MarkoMZ** [scaleflex/js-cloudimage-360-view#112]
when supplying a image list, when requestResizedImages() is called, the images do not have the right source!

my guess is that a function sets the image-src to the format '[base-url-of-website]/images-[idx].jpg', which should not be done!

**Comment by amrw-js** [comment]
hey @MarkoMZ, we are going to fix this issue in the next release.

**Comment by amrw-js** [comment]
hey @PedroVentura235, it should be this week

**Comment by amrw-js** [comment]
hey @PedroVentura235 , fixed on [v2.7.2](https://github.com/scaleflex/js-cloudimage-360-view/releases/tag/v2.7.2)

**Comment by PedroVentura235** [comment]
Hey, in my website id still didnt fix it, the error is the same : sets the image-src to the format '[base-url-of-website]/images-[idx].jpg'. 
Website : https://bvansiao.pt/galerias/veiculos-combate/

**Comment by amrw-js** [comment]
hey @PedroVentura235, 
please make sure that you are using [data-image-list-x](https://github.com/scaleflex/js-cloudimage-360-view#data-image-list-x-or-data-image-list-x)  in the right way 
if you are going to get the images from a server you have to [refer to the folder](https://github.com/scaleflex/js-cloudimage-360-view#data-folder-or-folder
) that includes your images. 
then use  [data-image-list-x](https://github.com/scaleflex/js-cloudimage-360-view#data-image-list-x-or-data-image-list-x) in this way 
```javascript
   "iris-1.jpeg",
   "iris-4.jpeg",
```
Or you can remove `data-folder` by adding the images paths in this way so you don't need to add `data-folder`

```javascript
   "https://scaleflex.airstore.io/demo/360-car/iris-12.jpeg",
   "https://scaleflex.airstore.io/demo/360-car/iris-15.jpeg"
```
but what I see on your website is that you are implementing the images in the wrong way 
![image](https://user-images.githubusercontent.com/81330789/151349399-36eb46a5-3c7a-4426-9df8-50775cc8197f.png)

**Comment by PedroVentura235** [comment]
Hi, i am using the right way, i think .
In the previous version it worked, but those errors appears the same, and sometimes didnt work. 
Because of the framework I am using I cant appoint directly to a folder, but i appoint directly path
![image](https://user-images.githubusercontent.com/51510658/151352515-1e2e3096-0794-4c17-81c1-f88c77a893ef.png)

**Comment by amrw-js** [comment]
@PedroVentura235 you have to replace ~`data-image-list`~ with `data-image-list-x` as it was [deprecated](https://github.com/scaleflex/js-cloudimage-360-view#data-image-list-x-or-data-image-list-x) from the previous version.
tested on my side it works
```html
<div
             class="cloudimage-360"
             data-image-list-x='["https://bvansiao.pt/media/0ucnfuif/rato_2.jpg"]'
             data-speed="50"
             data-responsive="scaleflex">
</div>
```

**Comment by PedroVentura235** [comment]
Didn´t notice that change. yes That was it ;-) 
Nice work and thanks

**Comment by PedroVentura235** [comment]
Hi, does version 2.7.2 became offline?
