### ISSUE TITLE
disable zoom

### ISSUE THREAD

**Issue by R-154** [scaleflex/js-cloudimage-360-view#114]
Is there a way to disable zoom and icon change (onclick)?
I now set these values to disable zoom, but the icon keeps changing.

`pointer-zoom-factor={0}`
`pinch-zoom-factor={0}`
`max-scale={100}`

**Comment by amrw-js** [comment]
hey @R-154, you should use 
disable-pointer-zoom
disable-pinch-zoom

**Comment by R-154** [comment]
Tested this, but that still changes the mouse cursor when you click on the image.

**Comment by amrw-js** [comment]
@R-154, we will fix this in the next release it should be this week

**Comment by amrw-js** [comment]
hey @R-154, fixed on [v2.7.2](https://github.com/scaleflex/js-cloudimage-360-view/releases/tag/v2.7.2)
