### ISSUE TITLE
Add left padding on filename

### ISSUE THREAD

**Issue by ChoOo7** [scaleflex/js-cloudimage-360-view#12]
const src = `${this.folder}${this.filename.replace('{index}', this.activeImage)}`;

If ma files are named
test-001.jpg
test-002.jpg

I can't use this plugin

I think it's quite simple to add an option to specify a left padding on filename

Thanks

**Comment by dzmitry-stramavus** [comment]
@ChoOo7 , hey

yep, I'll add it in next release. thx!

**Comment by dzmitry-stramavus** [comment]
@ChoOo7 , implemented in **v2.2.0**

doc: https://github.com/scaleflex/js-cloudimage-360-view/blob/master/README.md#data-index-zero-base-or-index-zero-base
