### ISSUE TITLE
Can I Prevent Play Behavior spin-y ?

### ISSUE THREAD

**Issue by kimbongjun** [scaleflex/js-cloudimage-360-view#137]
Hi,
Thank you for making a great library.

I have a one question.
Can I Prevent Play Behavior spin-y ?

I only want 360 events to happen spin-x.
Because Behavior spin-y can't scroll on mobile device.

Can you tell me the solution?

Thanks.

**Comment by amrw-js** [comment]
hey @kimbongjun,
by default, the spin y behavior is not allowed
it will be on only if you set value to [data-filename-y](https://github.com/scaleflex/js-cloudimage-360-view#data-filename-y-or-filename-y) or [data-image-list-y](https://github.com/scaleflex/js-cloudimage-360-view#data-image-list-y-or-data-image-list-y) attributes
