### ISSUE TITLE
cloudimage-360-left and cloudimage-360-right elments are never created

### ISSUE THREAD

**Issue by dotnetwise** [scaleflex/js-cloudimage-360-view#139]
And the same for the top and bottom
I think you had them before and removed that code

Adding `data-keys` doesn't display them

**Comment by amrw-js** [comment]
hi @dotnetwise , 
if you need to display the control elements you have to use 
`data-controls`

**Comment by dotnetwise** [comment]
Yes, but they are not rendered / it is a bug
Not in your examples either, sometimes they show up, other times they just
don't

**Comment by amrw-js** [comment]
hey @dotnetwise, can you please show me the bug in a codesandbox?

**Comment by DATEx2** [comment]
unfortunately we no longer use your product as it was not mobile friendly (touch, pan & zoom, double tap etc.) - we use a better one (suited for our mobile experience needs instead), so I can no longer help with the repo, but I believe you can try on your page with your phone and see if it always renders correctly. It was randomly doing nothing and randomly working (race events due to different loading events, I suppose)

**Comment by amrw-js** [comment]
hey @DATEx2,  the touch events have been fixed in [v3.1.0](https://github.com/scaleflex/js-cloudimage-360-view/releases/tag/v3.1.0). while panning, and zoom is a feature we already added to our roadmap.

**Comment by joshsedl** [comment]
`data-controls`? On your demo page, it says `data-control`:
![image](https://github.com/user-attachments/assets/e066e18a-8b31-4fff-b35d-8d33a3864e6f)

And the feature is also not documented:
https://github.com/scaleflex/js-cloudimage-360-view?tab=readme-ov-file#-config

**Comment by joshsedl** [comment]
But this is definitly a bug, simply adding `data-control` won't show any controls. They have to be added manually, see https://codesandbox.io/s/js-cloudimage-360-view-example-forked-m57v8c?file=/index.html.

**Comment by joshsedl** [comment]
Unfortunately, I don't have the permissions to change the label of this issue nor the issue title.

**Comment by DATEx2** [comment]
> Unfortunately, I don't have the permissions to change the label of this issue nor the issue title.

and what would be a correct title and label?

**Comment by joshsedl** [comment]
label: `bug`
title: `Setting data attribute "data-control" won't render arrow controls (cloudimage-360-left, cloudimage-360-right, etc.)`
