### ISSUE TITLE
View Image

### ISSUE THREAD

**Issue by jacknumpty** [scaleflex/js-cloudimage-360-view#14]
Hi, great plugin. Is it possible to get the {index} of the image that is being viewed?

When you have rotated the image or when the image has loaded I would like to know which image is being viewed.

data-filename="myimage_{index}.jpg"

Thanks!

**Comment by dzmitry-stramavus** [comment]
@jacknumpty , yes, it's good to have such information. I'll add an easy way to get this info. ETA 1-2 weeks

**Comment by dzmitry-stramavus** [comment]
implemented in **v2.3.0**
docs: https://github.com/scaleflex/js-cloudimage-360-view/blob/master/README.md#getactiveindexbyid
