### ISSUE TITLE
When only 360° horizontal is allowed, allow vertical scroll

### ISSUE THREAD

**Issue by dotnetwise** [scaleflex/js-cloudimage-360-view#143]
Currently, the `vertical scroll` is `eaten` which is not a good experience, especially on mobile

**Comment by amrw-js** [comment]
@dotnetwise, we added this fix to our roadmap

**Comment by amrw-js** [comment]
hey @dotnetwise,
fixed in [v3.1.0](https://github.com/scaleflex/js-cloudimage-360-view/releases/tag/v3.1.0)
