### ISSUE TITLE
Insert image from local folder

### ISSUE THREAD

**Issue by williamchristianc** [scaleflex/js-cloudimage-360-view#145]
Capability to insert the image from the local folder

**Comment by fadyromany** [comment]
i have the same issue

**Comment by amrw-js** [comment]
hey @williamchristianc, @fadyromany 
pls check [data-image-list-x (or data-image-list-x)](https://github.com/Scaleflex/js-cloudimage-360-view#data-image-list-x-or-data-image-list-x)
