### ISSUE TITLE
Touch Not Working On Windows Browsers

### ISSUE THREAD

**Issue by azuregithubrepo** [scaleflex/js-cloudimage-360-view#146]
Hi Does, the latest version of the slider works with touch devices. I am not able to use the touch to drag and rotate the objects on windows machine. While it does work on mobile devices but the same fails to work on Windows browsers. Tried firefox, chrome and edge and it does not work. Any help will be greatly appreciated.

Thanks
Siddharth

**Comment by amrw-js** [comment]
fixed in [v3.1.0](https://github.com/scaleflex/js-cloudimage-360-view/releases/tag/v3.1.0)
