### ISSUE TITLE
Multiple instances of the plugin , doesn't show the same active image as 1

### ISSUE THREAD

**Issue by amruth0983** [scaleflex/js-cloudimage-360-view#15]
Hi, 

First of all great plugin, kudos to you guys. We have been adapting to our application and recreating the same magic within our application. We came across a issue regarding the rendering the first active image. We followed the same implementation which was shown in 
https://codesandbox.io/s/6479n17j73?fontsize=14&module=%2Findex.html , we have two instances just like in the example. Instead of 36 images, we have 100 images for both instances. Now when we reload the application the both instances active image are kept on changing instead of showing 1. When I checked your demo sandbox, it happens same on that as well.. Can we have all the multiple instances with active image as 1 instead of changing? 

Do let me know if you need any inputs from my side

**Comment by dzmitry-stramavus** [comment]
@amruth0983 hey,

thx for opening, will check for next release

**Comment by dzmitry-stramavus** [comment]
hey @amruth0983 ,

looks like it was fixed in previous releases.
