### ISSUE TITLE
Skipping last image

### ISSUE THREAD

**Issue by milleker** [scaleflex/js-cloudimage-360-view#16]
Good evening,

I've started using this script and at first thought the last image was skipping on autoplay. With autoplay off, it's still skipping the last image, however only when dragging the image counter clockwise. If I drag clockwise, the last image is present. 

Version: 2.1.0
Browser: Firefox, Chrome.
16 images, speed 250.

**Comment by dzmitry-stramavus** [comment]
done in #17, will be merged in next release

**Comment by dzmitry-stramavus** [comment]
fixed in **v2.2.0**
