### ISSUE TITLE
Option to add list of photo instead of `folder` & `filename`

### ISSUE THREAD

**Issue by newhope** [scaleflex/js-cloudimage-360-view#18]
As the title, I think it'll be better to have an option for list of photos.
eg: `data-photolist="['path/abc.jpg','to/xyz.jpg']"`

Reason: maintaining of incremental photo filename is require a lot more effort in many CMS (eg: Wordpress)

**Comment by dzmitry-stramavus** [comment]
@newhope , hey

agree 
we will add this option in next release

**Comment by dzmitry-stramavus** [comment]
@newhope , implemented in **v2.2.0**

doc: https://github.com/scaleflex/js-cloudimage-360-view/blob/master/README.md#data-image-list-or-image-list
