### ISSUE TITLE
Magnifier doesn't work when you use a data-image-list

### ISSUE THREAD

**Issue by tasmaniaman** [scaleflex/js-cloudimage-360-view#21]
Hey, Love your plugin.

I'm using a data-image-list instead of a folder path like the below:
`<div
   class="cloudimage-360"
		data-image-list='[
   "https://mysite.com/assets/alt_11/SPD1R.jpg",
   "https://mysite.com/assets/alt_12/SPD1R.jpg",
   "https://mysite.com/assets/alt_13/SPD1R.jpg",
   "https://mysite.com/assets/alt_14/SPD1R.jpg",
	 "https://mysite.com/assets/alt_15/SPD1R.jpg",
	 "https://mysite.com/assets/alt_16/SPD1R.jpg",
	 "https://mysite.com/assets/alt_17/SPD1R.jpg",
	 "https://mysite.com/assets/alt_18/SPD1R.jpg"]'
	 data-magnifier="2">`

Everything is working fine except when I try and use the magnifier, you get an endless load icon and in the console.log it shows that its trying to load the current image from the root folder: `GET https://mysite.com/image-8.jpg 404`

Am I missing a setting or is this a bug?

**Comment by dzmitry-stramavus** [comment]
hey @tasmaniaman

fixed in **v2.3.1**
