### ISSUE TITLE
add hotspot

### ISSUE THREAD

**Issue by ahmedAlmasri** [scaleflex/js-cloudimage-360-view#22]
hot to add hotspot in 360 view

**Comment by dzmitry-stramavus** [comment]
hey @ahmedAlmasri,

yeah, it's on our roadmap

**Comment by koentjuh1** [comment]
What is the status of this feature?

Is it possible to add the index or the current image as a Class when drag is used. Like when image1 is active the class="cloudimage-360 initialized **image1**" and when image2 is actiave the class="cloudimage-360 initialized **image2**" etc

is this possible right now?

Thanks for your time :)

**Comment by atul-bajpai** [comment]
is this feature available now

**Comment by dzmitry-stramavus** [comment]
unfortunately, not yet

**Comment by EasonSun** [comment]
Hi @dzmitry-stramavus How is the progress? Can I help to complete this feature? Thx!

**Comment by dzmitry-stramavus** [comment]
hey @EasonSun , sure you can send your implementation and I validate it.

**Comment by amrw-js** [comment]
hey @ahmedAlmasri,
we have implemented this feature in [v3.0.0](https://github.com/scaleflex/js-cloudimage-360-view/releases/tag/v3.0.0)
kindly read [Hotspots or Markers](https://github.com/scaleflex/js-cloudimage-360-view#-hotspots-or-markers) documention
