### ISSUE TITLE
X spin plus Y ?

### ISSUE THREAD

**Issue by jesfx** [scaleflex/js-cloudimage-360-view#23]
I've got a slew of images naming convention of 'filename-01-01.jpeg' so I'm running into trouble displaying them as they have a column and a row number, not just one as required for this app. Short from renaming every file and forgetting the Y axis rotation, is there a way to use my files with two numbers instead of one ?

**Comment by dzmitry-stramavus** [comment]
hey @jesfx, 

yeah, probably a good thing to add in our plugin. I'll see when we can add Y spin.

**Comment by falkogloeckler** [comment]
Adding an Y spin would be great! Any news on this?

**Comment by dzmitry-stramavus** [comment]
hey @falkogloeckler , for now this feature is postponed as our clients didn't ask for it. Currently it's minor status in backlog

**Comment by uvex-na** [comment]
Hello @dzmitry-stramavus, 
do you know when the feature will be ready? 

I'm looking for a 360 degree solution for the company I work for. 
They want a solution that can rotates in both directions.

**Comment by amrw-js** [comment]
hey, you can reach out to this feature in the latest version [2.7.0](https://github.com/scaleflex/js-cloudimage-360-view/releases/tag/2.7.0)
