### ISSUE TITLE
Index is not defined when used the Lazyload

### ISSUE THREAD

**Issue by MatHackDev** [scaleflex/js-cloudimage-360-view#24]
Hello; 
When i active the lazyload with plugin lazysizes, i'm receive this error (it's works if disable the lazyload) :

Dom Code
```
<section>
            <div class="cloudimage-360"
                data-folder="/assets/img/wheel/"
                data-filename="wheel-{index}.jpeg"
                data-amount="70"
                 data-ratio="0.86"
                 data-autoplay
                 data-bottom-circle
                 data-lazyload></div>
</section>
```

![image](https://user-images.githubusercontent.com/11650888/69815666-14b19c80-11f7-11ea-9209-5671a89b9e89.png)
![image](https://user-images.githubusercontent.com/11650888/69815717-3579f200-11f7-11ea-9f39-55fc91d696bb.png)

**Comment by dzmitry-stramavus** [comment]
hey @MatHackDev ,

fixed in **2.3.2**
