### ISSUE TITLE
Translate the view360Icon?

### ISSUE THREAD

**Issue by verbeeksteven** [scaleflex/js-cloudimage-360-view#25]
Hello,

Is there a way to provide a custom SVG or translate the view360Icon?

I need to translate it to French.

Thanks,

**Comment by dzmitry-stramavus** [comment]
hey @verbeeksteven ,

yes, we will add the feature in next release

**Comment by ivangretsky** [comment]
Maybe provide an option to define own icon?

**Comment by twilco** [comment]
Also wanted to mention I'd love the ability to define a custom "360 view" SVG icon.  Any idea when the next release is slated to be complete?  Or, if this work still needs to be done, I may also be interested in helping out.  Let me know if this is the case and I can take a look.

Thanks for your work on this project — it's really great!

**Comment by dzmitry-stramavus** [comment]
@twilco , thanks a lot for contributing! I'm just back from vacation. I'll release new version today

**Comment by dzmitry-stramavus** [comment]
**available in 2.6.0**
