### ISSUE TITLE
The engine remember last turn of image

### ISSUE THREAD

**Issue by MegoSoft** [scaleflex/js-cloudimage-360-view#28]
Hello. I am using your "plugin" in wordpress, it works fine, but when I left the turned product (for example: I close the website with image turned to image4), and reopen the site, the viewer is set to image4. I would like to set viewer to image1 every time I open the website. How can I do that? I have found no javascript cookies, or similar inside the code.

Thank you a lot. Have a nice day

**Comment by dzmitry-stramavus** [comment]
#29
