### ISSUE TITLE
First preview image is random

### ISSUE THREAD

**Issue by pfranck** [scaleflex/js-cloudimage-360-view#29]
We are using your awesome 360° product viewer ( https://github.com/scaleflex/js-cloudimage-360-view ), but we have just one question:

We have implemented your code into WordPress custom template. We are using 9 images of a window’s profile. The problem is, that from time to time, the preview doesn’t start from image number 1, but it seems, the number is random.

Here’s the link on live version: http://dev.bajan.sk/rafaelwin/okenne-profily/

The first image should be with front view and opened window.

But from time to time, no 1st image is visible, when user open the site

This happen especially in Firefox, every time you refresh the page with F5, you get another turn of imageset.

How can I be safe, that first image will be always loaded at the opening of the site?

**Comment by dzmitry-stramavus** [comment]
**fixed in v2.4.0**
