### ISSUE TITLE
controls are backward

### ISSUE THREAD

**Issue by cup** [scaleflex/js-cloudimage-360-view#3]
if i drag from left to right - it should rotate counterclockwise but its doing the opposite

https://scaleflex.github.io/js-cloudimage-360-view

**Comment by dzmitry-stramavus** [comment]
hey @cup, thx for reporting the problem. It's just for first 360 view in the demo page. The images were saved in opposite direction for this view. Anyway, it's good to have possibility to change spin direction for cases like this, we will add the property **data-spin-direction="reverse"** for it

**Comment by dzmitry-stramavus** [comment]
**available in v2.0.2**

Now we can change spin direction by adding **data-spin-reverse** attribute

https://github.com/scaleflex/js-cloudimage-360-view#data-spin-reverse-or-spin-reverse

demo is updated: https://scaleflex.github.io/js-cloudimage-360-view
