### ISSUE TITLE
Server responded with a status of 429

### ISSUE THREAD

**Issue by saisanthoshdav** [scaleflex/js-cloudimage-360-view#30]
I tried to setup a 360 degree view with this plugin and have the following
- 40 images around 40kb each
- All images hosted on a S3 bucket

But some of the images are not pulled in with the 429 Too Many Requests response. I have similar behavior when the images are hosted on another of my web servers. Is there a good way to handle this by
a) Adding small delay between image requests
b) Raise requests for missing images again ?

I understand the response is coming from S3 for requesting too many images too soon, I am looking for a decent way of handling cases like this. 

Any suggestions / help on this matter would be greatly appreciated.

**Comment by dzmitry-stramavus** [comment]
hey @saisanthoshdav ,

Are you using Cloudimage to store your images?

**Comment by saisanthoshdav** [comment]
Images were hosted on one of my web server machines. The issue randomly disappeared the next idea so I let it be. Is this expected for images that are not hosted on Cloudimage ?

**Comment by dzmitry-stramavus** [comment]
It happens but very rare.
