### ISSUE TITLE
Add a normal zoom effect

### ISSUE THREAD

**Issue by Kryuko** [scaleflex/js-cloudimage-360-view#31]
Hello.
I've downloaded the library and im trying to edit the unminified file to add a standard-zoom function.

Actually, i've managed to edit the update function with a doubled size with this command:
t.drawImage(e, '-'+(r/2) , '-'+(a/2) , this.canvas.width * 2, this.canvas.height * 2)

My problem is that i need to add an eventlistener onclick, so i can activate my custom zoom function when you just click on the main image.
How can i add that? I've seen the whole code but im not too expert in JS and i don't understand how can i add my custom listener to the library.

Thank you in advance.

**Comment by dzmitry-stramavus** [comment]
hey @Kryuko ,

Sorry for the late reply, it was a hectic time. What kind of zoom effect you would like to have?

**Comment by amrw-js** [comment]
hey @Kryuko, we have implemented pointer-zoom/pinch-zoom in [v2.7.0](https://github.com/scaleflex/js-cloudimage-360-view/releases/tag/2.7.0)

**Comment by amrw-js** [comment]
hey@Kryuko, kindly check the new [pointer-zoom](https://github.com/scaleflex/js-cloudimage-360-view#data-pointer-zoom-or-pointer-zoom) feature

**Comment by Kryuko** [comment]
Sorry for the late reply @amrw-js , unfortunately i'm no longer using this library because i moved to other projects that don't require this feature. I'll surely let you know something if i'll use it again.
