### ISSUE TITLE
keyboard control direction strangely linked with autoplay direction

### ISSUE THREAD

**Issue by akito6776** [scaleflex/js-cloudimage-360-view#34]
Another strange behavior I noticed was with the "data-keys" option, which enables keyboard control of the 360 viewer.

I see in the code that the direction for the keyboard arrows are linked to the autoplay direction for some very strange reason.

Here's the relevant section of the code, which is the keydown() function. I can see that the 37 and 39 key codes (left and right arrow on keyboard) conditionally call this.prev() and this.next() based on "this.reversed".
```
keydown(event) {
  ...
  if ([37, 39].includes(event.keyCode)) {
    if (37 === event.keyCode) {
      if (this.reversed)
        this.prev();
      else
        this.next();
    } else if (39 === event.keyCode) {
      if (this.reversed)
        this.next();
      else
        this.prev();
    }

    this.onSpin();
  }
  ...
}
```

I can see that "this.reversed" is set within the init() function and it is set to "autplayReverse".

```
init(container) {
   ...
  this.reversed = autoplayReverse;
   ...
}
```

I find this to be super confusing (that the autoplay direction is for both autoplay and keyboard control) and I think others may feel the same way too. I'm sure not everyone would agree this is exactly a bug, per say, but this still seems like an issue that will cause a lot of confusion.

Can the official dev add a new data option for the keyboard control direction? Something like "data-keys-reverse", which sets the direction purely for the keyboard control? This way, the keyboard control and autoplay direction would no longer be strangely linked together.

**Comment by amrw-js** [comment]
hey @akito6776, 
thanks for your feedback
you can [reverse the keyboard keys](https://github.com/scaleflex/js-cloudimage-360-view#data-keys-reverse-or-keys-reverse)
```javascript
data-reverse-keys
````
