### ISSUE TITLE
How to customize preloaders

### ISSUE THREAD

**Issue by ivangretsky** [scaleflex/js-cloudimage-360-view#35]
Good day!
Thanks for a cool and very useful plugin! 

Is there an easy way to customize the preloader? There are actually two of them. The stripe at the top and the percents counter in the middle. I need to turn off the upper stripe/progress bar thing or move it to the bottom and change its color. Is that possible?

**Comment by dzmitry-stramavus** [comment]
hey @ivangretsky,

Yes, we can make it customizable. I added it to our roadmap. However, I cannot say ETA. Currently, our team is busy with releasing our next products.

**Comment by ivangretsky** [comment]
Thanks for your answer.
So now it is not possible with css?

**Comment by amrw-js** [comment]
hey @ivangretsky, you can customize all icons with CSS in the latest version  [2.7.0](https://github.com/scaleflex/js-cloudimage-360-view/releases/tag/2.7.0)
you can hide the icons bar by adding the following styles to it
`display:none;`
or move it with margins
