### ISSUE TITLE
Chrome warning for non passive event-listener

### ISSUE THREAD

**Issue by matteobad** [scaleflex/js-cloudimage-360-view#37]
Hi @dzmitry-stramavus, thanks for the great work!
I've noticed this warning on the console and I think it is caused by this event listener.

In addition this kind of optimization should be necessary only on touchstart and touchmove but not in touchend. It could also be useful to apply a passive listener only if supported. Something like:

```js
applyPassive() {
	if (this._supportsPassive !== undefined) {
		return this._supportsPassive ? { passive: true } : false
	}

	// feature detect
	let isSupported = false
	try {
		document.addEventListener('test', null, {
			get passive() {
				isSupported = true
			},
		})
	} catch (e) {
		// do nothing
	}

	this._supportsPassive = isSupported
	return this.applyPassive()
}
```

https://github.com/scaleflex/js-cloudimage-360-view/blob/8db632aeb8f2ba394852afa21623940785feada5/src/ci360.service.js#L756

If you think this could be done I would be happy to prepare a PR

**Comment by dzmitry-stramavus** [comment]
hey @matteobad ,

**Comment by amrw-js** [comment]
hey @matteobad, 
Thanks for the feedback!
would you kindly provide me reproducing steps ?

**Comment by amrw-js** [comment]
hey @matteobad, we have removed this warning in [v2.7.0](https://github.com/scaleflex/js-cloudimage-360-view/releases/tag/2.7.0)
