### ISSUE TITLE
Object Fit by parent element not possible

### ISSUE THREAD

**Issue by moorl** [scaleflex/js-cloudimage-360-view#39]
Hi, thanks for this plugin!

I need help to fit the canvas element by its parent.  Actually the 360 degree image is cut at the bottom:

![image](https://user-images.githubusercontent.com/45460948/87876017-5b961180-c9d5-11ea-967c-b26c2ab31b78.png)

**Comment by dzmitry-stramavus** [comment]
hey @moorl ,

**Comment by dzmitry-stramavus** [comment]
hey @moorl ,

It can be an option in the future releases. Possibility to set width/height and fit. 

Meantime, you can fix it by applying styles to canvas     
```
max-width: 100%;
height: auto; 
```

and as you know the ratio of your images, you can calculate width of canvas' container

**Comment by canyonx** [comment]
Hi, great plugin, used for wood sculptures, 

Same problem here cannot fix the image height by the style..
it's works well to fix the width by style="width: 400px; "
But cannot fix the image with style="max-height: 100vh; "

the height of the div is fixed but the image owerflow

**Comment by amrw-js** [comment]
hey @moorl @canyonx, It's a nice feature. it will be available on the next release

**Comment by amrw-js** [comment]
it's is available now on our latest version to set [data-width](https://github.com/scaleflex/js-cloudimage-360-view#data-width-or-width) or [data-height](https://github.com/scaleflex/js-cloudimage-360-view#data-height-or-height)
so you can fit the canvas relative to the width or height and maintain the aspect ratio as well as you can add both of them
