### ISSUE TITLE
Image viewer disapears on resize window

### ISSUE THREAD

**Issue by moorl** [scaleflex/js-cloudimage-360-view#40]
The image viewer doesn't handle window resize, the image just disapears and don't come back.

**Comment by dzmitry-stramavus** [comment]
@moorl , can you please describe more? steps to reproduce or better record a small video with the bug. Thx

**Comment by moorl** [comment]
@dzmitry-stramavus this bug is caused by DOM manipulation of an other JavaScript. So its not a bug, but maybe the 360-viewer could re-init by window resize events?

**Comment by dzmitry-stramavus** [comment]
it's not a good idea to do inside plugin, but you can do it on your side.
