### ISSUE TITLE
data-autoplay on mobile

### ISSUE THREAD

**Issue by agrubiy** [scaleflex/js-cloudimage-360-view#42]
Hello. 
There are some troubles then I use "data-autoplay" . 
It work perfect on desctop, but don't work on mobile. 
Does anyone have thought hove to fix this moment?

Example on CodeSandbox https://codesandbox.io/s/js-cloudimage-360-view-controls-q9gsy

**Comment by dziopak** [comment]
Remove
`&& !this.isMobile,`
From
`(this.autoplay = y && !this.isMobile),`

in the source code :)

**Comment by amrw-js** [comment]
hey @agrubiy, we have fixed it in [v.2.7.0](https://github.com/scaleflex/js-cloudimage-360-view/releases/tag/2.7.0)
