### ISSUE TITLE
change width and height of canvas element

### ISSUE THREAD

**Issue by rein96** [scaleflex/js-cloudimage-360-view#44]
Tried to change the width and height of the canvas, because the images are too big.

But it did not work. 

`document.getElementsByTagName('canvas')[0].style = 'width: 600px';`

```
  let canvas = document.getElementsByTagName('canvas')[0];
  canvas.width = 600;
  canvas.height = 600;
```
Any ideas ? Thanks before 😊

**Comment by dzmitry-stramavus** [comment]
Hello @rein96 ,

Sorry for the later reply. Change not canvas but it's container.
