### ISSUE TITLE
How to open the 360-view inside a modal

### ISSUE THREAD

**Issue by Mobiliar3D** [scaleflex/js-cloudimage-360-view#48]
Hello, 

I'm trying to open the 360-view inside a modal, but the modal loads empty, showing only the 360º view icon. On mouse drag, the image appears. 

Is there a way to load the first image automatically, just like loading the 360-view directly on the page?

Thanks,

**Comment by DenysRoshchin** [comment]
In my case helped data-autoplay="true". Without this, I have the same issue

**Comment by Mobiliar3D** [comment]
> In my case helped data-autoplay="true". Without this, I have the same issue

Thanks, but I didn't want it to autoplay...

**Comment by amrw-js** [comment]
hey @Mobiliar3D, we have fixed it in [v2.7.0](https://github.com/scaleflex/js-cloudimage-360-view/releases/tag/2.7.0)
