### ISSUE TITLE
How to use function getActiveIndexByID()?

### ISSUE THREAD

**Issue by nicktoot** [scaleflex/js-cloudimage-360-view#49]
Hi, the getActiveIndexByID (https://github.com/scaleflex/js-cloudimage-360-view#getactiveindexbyid) function is not working for me. It always return 'undefined'. window.CI360._viewers array is empty.

Are there any examples? To which event bind it? Are there any hotspots planned in the future?

Thank you!

**Comment by dzmitry-stramavus** [comment]
hey @nicktoot ,

if you send a quick codesandbox, we can check the problem faster.

"Are there any hotspots planned in the future?"

yes, it's on our roadmap for nearest future

**Comment by nicktoot** [comment]
I am sorry, maybe I made a mistake in my code in codesandbox, now it works :) Can you please tell me to which event i can bind it (so that when you move the mouse or finger, i constantly get the current image index)?

**Comment by dzmitry-stramavus** [comment]
for now we don't emit any events. Alternative way you can achieve it is just add event listener "on mouse move" and get current index with getActiveIndexByID
