### ISSUE TITLE
drag-speed ?

### ISSUE THREAD

**Issue by HeuHax** [scaleflex/js-cloudimage-360-view#5]
Would it be possible to get an attribute to control the drag speed? 
Our client find it to be a bit slow :)

Also "data-autoplay" / "autoplay" doesn't work because it's not cast as a bool, so it's always true :)

Cheers

**Comment by dzmitry-stramavus** [comment]
hey @HeuHax ,

fixed problem with bool types 

added drag-speed/data-drag-speed attribute 

updates available in **v2.0.6**

**documentation**: https://github.com/scaleflex/js-cloudimage-360-view#data-drag-speed-or-speed

**demo** for drag-speed: https://codesandbox.io/s/jscloudimage360view-dataspeed-example-mi2v3?fontsize=14

updates available in v2.0.6

Happy coding!

**Comment by HeuHax** [comment]
Amazing! Thanks a lot ! :)

**Comment by HeuHax** [comment]
I'm running into weird problems with this.

It seems to work great in chrome when i have developer console (F12) open, but when i close it speed goes back to default.
Also it doesn't seem to work at all in firefox.

Example here:
http://salient.biofarma.dk/salientgel

I do have 301 images, so that might cause it because some delay maybe ? I dunno ...

**Comment by dzmitry-stramavus** [comment]
@HeuHax , ok, yes, it might be the problem. I'll check when I have time during the week

**Comment by dzmitry-stramavus** [comment]
@HeuHax , **fixed**

updates available in **v.2.0.7**

demo: https://codesandbox.io/s/jscloudimage360view-sivbj

Happy coding!

**Comment by HeuHax** [comment]
The speed is real!

Thanks a lot ! 😃
