### ISSUE TITLE
Changing the colour of the magnifying glass icon?

### ISSUE THREAD

**Issue by lydiatsai** [scaleflex/js-cloudimage-360-view#50]
Is there any way I can change the colour of the magnifying glass icon using CSS? 

My image backgrounds have a similar colour to it, so the icon isn't visible to my users currently.

I am looking for a selector that will only affect the magnifying glass and not the general "360 view" circle that appears in the centre of the image.

**Comment by dzmitry-stramavus** [comment]
hey @lydiatsai , we will add CSS selector and param to change colour of icons next release

**Comment by amrw-js** [comment]
hey @lydiatsai, you have the possibility to customize icon styles in the latest version [2.7.0](https://github.com/scaleflex/js-cloudimage-360-view/releases/tag/2.7.0)
