### ISSUE TITLE
[Feature] Zoom with mouse wheel 

### ISSUE THREAD

**Issue by Mboudali** [scaleflex/js-cloudimage-360-view#55]
Hi,
Can you implement a mouse wheel zoom feature?
Similar to navigation in a CAD software: scroll to zoom in/out. Click and drag to rotate.

**Comment by dzmitry-stramavus** [comment]
hey @Mboudali , yes, it can be nice way to zoom. I'll add it to our roadmap. Thx

**Comment by amrw-js** [comment]
hey @Mboudali, we have implemented this feature in [v2.7.0](https://github.com/scaleflex/js-cloudimage-360-view/releases/tag/2.7.0)

**Comment by Mboudali** [comment]
Great!
