### ISSUE TITLE
[bug?] Zoom in full screen

### ISSUE THREAD

**Issue by Mboudali** [scaleflex/js-cloudimage-360-view#56]
The magnifier disappears in full screen mode.

**Comment by amrw-js** [comment]
hey @Mboudali, we have implemented this feature in [v2.7.0](https://github.com/scaleflex/js-cloudimage-360-view/releases/tag/2.7.0)
check [data-magnifier-in-fullscreen](https://github.com/scaleflex/js-cloudimage-360-view#data-magnifier-in-fullscreen-or-magnifier-in-fullscreen )in the documentation

**Comment by Mboudali** [comment]
Great! Thank you.
