### ISSUE TITLE
cloudimg.io discontinued?

### ISSUE THREAD

**Issue by drpark** [scaleflex/js-cloudimage-360-view#58]
Hi, scaleflex.cloudimg.io seems down for several days.
How to fix the problem?

thank you

**Comment by drpark** [comment]
no we have "Error 406: This domain might not be allowed by your configuration.
Change it yourself in your configuration, or contact hello@cloudimage.io
You can login to your Cloudimage console, click on Image Settings in the side menu, then configure the Whitelisted domains section. After clicking SAVE, the new whitelisted domains should be ready in less than 120 seconds."

thank you

**Comment by drpark** [comment]
@dzmitry-stramavus can you tell me what is happening? thank you

**Comment by dzmitry-stramavus** [comment]
hey @drpark 

You are using demonstration cloudimage tokens. Those tokens are exclusive for the demonstration and customers must have own accounts/tokens to use the plugins.

Note that
- the plugin is free to use
- but the cloudimage CDN is not

**Comment by drpark** [comment]
Ah ok sorry. I didn't undestood like this ^^
because it was working by just cut and pasting the script before 
ok thank you for the answer
