### ISSUE TITLE
initial plugin with local images

### ISSUE THREAD

**Issue by omidkh68** [scaleflex/js-cloudimage-360-view#6]
Hey guys,
We want to use local images in this plugin, but not working with local path in data-folder attribute.
How can we fix that?

**Comment by dzmitry-stramavus** [comment]
hey @omidkh68 ,

Can you show me your code to have more input? 

pls, check the working example below
![image](https://user-images.githubusercontent.com/10708539/59145596-d0370800-89ee-11e9-8441-7f86c822eb44.png)

**Comment by omidkh68** [comment]
@dzmitry-stramavus 
problem solved, Tnx 👍
