### ISSUE TITLE
data-autoplay once

### ISSUE THREAD

**Issue by AxelF1977** [scaleflex/js-cloudimage-360-view#60]
Hi,

is there a way, to data-autoplay once and than stop automaticly?

Thanks

**Comment by dzmitry-stramavus** [comment]
hey @AxelF1977 ,  It's a nice enhancement. I'll add this to our roadmap. (will be done in next release)

**Comment by Uranbold** [comment]
Really need this feature :)

**Comment by amrw-js** [comment]
hey @AxelF1977, you can reach out to this feature in [v2.7.0](https://github.com/scaleflex/js-cloudimage-360-view/releases/tag/2.7.0)
check [data-play-once](https://github.com/scaleflex/js-cloudimage-360-view/blob/master/README.md#data-play-once-or-autoplay)
