### ISSUE TITLE
Need plugin images locally

### ISSUE THREAD

**Issue by oblivionbees** [scaleflex/js-cloudimage-360-view#62]
The plugin images are not available in the local folder but are being pulled from scaleflex for 
eg._'https://scaleflex.ultrafast.io/https://scaleflex.airstore.io/filerobot/js-cloudimage-360-view/360_view.svg'_

plugin should fetch images from local folder. by change this it will be easier to apply branding/customization.

**Comment by nganchev** [comment]
Hi @oblivionbees ,

Those are default links and if you want you can change with custom or local files
![image](https://user-images.githubusercontent.com/67464754/108833647-c9db2c00-75d5-11eb-87bf-782fa17b23fc.png)

**Comment by amrw-js** [comment]
hey @oblivionbees, starting from [v2.7.1](https://github.com/scaleflex/js-cloudimage-360-view/releases/tag/2.7.1) all images can be modified by using CSS selectors to overwrite the default background-image.
