### ISSUE TITLE
Full 360 view

### ISSUE THREAD

**Issue by adnanafzal565** [scaleflex/js-cloudimage-360-view#69]
Hi.

Thanks for this project.

Right now, only the horizontal view is supported. Is there a way to get the full 360-degree view? Horizontally and vertically as well.

Thanks again.

**Comment by amrw-js** [comment]
hey @adnanafzal565, we have implemented this feature in [v2.7.0](https://github.com/scaleflex/js-cloudimage-360-view/releases/tag/2.7.0)
