### ISSUE TITLE
Q: Disable drag

### ISSUE THREAD

**Issue by zuhra031** [scaleflex/js-cloudimage-360-view#70]
Hello,

Is there any option to (completely) disable mouse/touch drag. I want to use only arrows for rotating.

Thanks,
G.

**Comment by amrw-js** [comment]
hey @zuhra031, please check [data-disable-drag](https://github.com/scaleflex/js-cloudimage-360-view/blob/master/README.md#data-disable-drag-or-disable-drag)

**Comment by bennydalpke** [comment]
While disable-drag is displayed on the demo-page, it's not part of the current js-file.
However, I was able to disable drag by setting data-drag-speed absurdly high and override the "cursor: grab" via css.

**Comment by amrw-js** [comment]
@bennydalpke nice idea,
 however, we have disable-drag feature starting from [v.2.7.0](https://github.com/scaleflex/js-cloudimage-360-view/releases/tag/2.7.0

**Comment by bennydalpke** [comment]
> @bennydalpke nice idea, however, we have disable-drag feature starting from [v.2.7.0](https://github.com/scaleflex/js-cloudimage-360-view/releases/tag/2.7.0)

Haha, what a timing. I was looking for a disable-drag function yesterday and came up with the idea - and today you publish a new version with a proper solution.
Thanks for you work! Really enjoyed working with your 360-view :-)
