### ISSUE TITLE
Close Fullsceen?

### ISSUE THREAD

**Issue by Uranbold** [scaleflex/js-cloudimage-360-view#74]
Hello,

Awesome JS. Really love it. I have 1 feature request. Can close the Fullscreen by clicking the ESC button on the keyboard? Not only clicking the close button.

Thanks.

**Comment by amrw-js** [comment]
hey @Uranbold, we have implemented this feature in [v2.7.0](https://github.com/scaleflex/js-cloudimage-360-view/releases/tag/2.7.0)
