### ISSUE TITLE
initial plugin with js

### ISSUE THREAD

**Issue by omidkh68** [scaleflex/js-cloudimage-360-view#8]
hey @dzmitry-stramavus,
We need to initialize plugin programmatically, how can we do it?

**Comment by dzmitry-stramavus** [comment]
@omidkh68 , hey

I'll add this possibility during the week. Busy with launching another project

**Comment by omidkh68** [comment]
@dzmitry-stramavus that's great, I'll waiting for your next release :)

**Comment by dzmitry-stramavus** [comment]
@omidkh68, hey!

available in **v2.1.0**

**doc**: https://github.com/scaleflex/js-cloudimage-360-view#init
**code sandbox**: https://codesandbox.io/s/js-cloudimage-360-view-initdestroy-y1il9
