### ISSUE TITLE
Resize?

### ISSUE THREAD

**Issue by nachog4** [scaleflex/js-cloudimage-360-view#88]
I find no way to set a size other than the original images files... is there no option to resize to some specific format or to adapt to parent container?

**Comment by SFX-Heroes** [comment]
Hello,

Please check the Cloudimage Responsive integration:
https://github.com/scaleflex/js-cloudimage-360-view#cloudimage-responsive-integration

**Comment by IlyasMakari** [comment]
Is there a method to resize without signing up for any services?
